debug: true

server:
  port: 9093
  servlet:
    context-path: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

spring:
  application:
    name: keycloak-service
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            provider: keycloak
#            client-id: blu-micro-client
#            client-secret: 9ac51cca-0cb8-4a3c-999e-c53a49af28aa
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:9090/api/login/oauth2/code/keycloak
#            scope: openid
#        provider:
#          keycloak:
#            issuerUri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
#            authorizationUri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
#            tokenUri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
#            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
#            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
#            user-name-attribute: name
#            user-info-authentication-method: header
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

# keycloak config set up v10.0.2
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: blu-micro
  bearer-only: true
  principal-attribute: preferred_username
  ssl-required: none
  use-resource-role-mappings: true
  resource: blu-micro-client
  credentials:
    secret: 9ac51cca-0cb8-4a3c-999e-c53a49af28aa
