debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: gateway-service