server:
  port: 9091

spring:
  application:
    name: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    register-with-eureka: false
    fetch-registry: false