### application eureka service ###

server:
  port: 1000
  servlet:
    context-path: /api

spring:
  application:
    name: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/api/eureka/
    register-with-eureka: false
    fetch-registry: false

# management
management:
  endpoints:
    web:
      exposure:
        include: '*'