debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/api/eureka/

server:
  port: 1001
  servlet:
    context-path: /api

spring:
  application:
    name: config-service
  # cloud configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/febrihasan/configuration.git
          search-paths: spring-boot-micro-keycloak
          default-label: main
  # database repository
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak_micro
    username: postgres
    password: postgres
  # flyway migration
  flyway:
    enabled: true
  # jpa / hibernate
  jpa:
    show-sql: true